### ISSUE TITLE
与 ox-beamer 的冲突

### ISSUE THREAD

**Issue by exaos** [tumashu/org2ctex#2]
环境：ArchLinux + emacs 26.1 + org-mode 9

问题：设置 beamer level 后无法正常导出。

重现步骤：
1. 在 org 文件头中添加 `#+OPTIONS: H:2`, 当打开 `(org2ctex-toggle t)` 时，执行 `org-export` 到 beamer 格式，会出现错误： `Wrong type argument: listp, org-beamer-sectioning`. 执行 `(org2ctex-toggle nil)` 之后，导出会正常，但中文字符处理不正确。
2. 不添加 `H:2`, 只添加 `#+BEAMER_FRAME_LEVEL: 2`, 可正常导出，但 beamer level 的设置失效。

**Comment by tumashu** [comment]
我试着修复了一下，但没法测试，你再试试吧
